### ISSUE TITLE
Crystal Cluster

### ISSUE THREAD

**Issue by AlleCraft-alterego** [Davoleo/Crystal-Glass#1]
- Da fixare la duplicazione se spostati da uno slimeblock (le ametiste avevano lo stesso bug ma lo hanno fixato)

- ~~Da fixare il rendering non si può vedere la parte in alto del cristallo interno dal lato (negli slimeblock e gli honeyblock non c'è il problema)~~
  - Sembra di qualcosa molto interno alla OpenGL e se si osserva bene anche gli honeyblock e gli slimeblock hanno lo stesso problema, solo meno noticeable a causa del loro modello interno meno complesso

- Cambiare gli stage da 8 a 4 (quindi scegliere e nel caso sistemare i modelli e la hitbox)

- Generazione nel mondo (da scegliere, la prima idea è aggiungere i cristalli nei pressi della lava per generazione simil-realistica o aggiungere la generazione simile a quella della ametista con della struttura e della lava)

- Automatizzazione per la generazione dei crystalli (da definire meglio, una struttura che genera cristalli)

- _oggetto per bloccare la crescita e metodo per rimuoverlo (TBD)_

**Comment by Davoleo** [comment]
> honeycomb per bloccare la crescita e l'ascia per rimuoverlo

avrebbe senso fosse un metallo come il rame che ci metti la cera per proteggerlo dalle intemperie e quindi bloccare l'ossidazione dovuto ad esse, posso capire il voler essere in linea, ma piuttosto facciamo un item apposta per bloccare la crescità se si vuole proprio fare.

**Comment by AlleCraft-alterego** [comment]
ok
